# Auto-generated by Python script: 8 pin commands

set_pin_physical_constraints -pin_name BSEL_o[0] -layers M3 -off_edge location -location {150.0 2325.845} -width 0.1
set_pin_physical_constraints -pin_name BSEL_o[1] -layers M3 -off_edge location -location {150.0 2150.165} -width 0.1
set_pin_physical_constraints -pin_name BSEL_o[2] -layers M3 -off_edge location -location {150.0 1974.485} -width 0.1
set_pin_physical_constraints -pin_name BSEL_o[3] -layers M3 -off_edge location -location {150.0 1798.805} -width 0.1
set_pin_physical_constraints -pin_name BSEL_o[4] -layers M3 -off_edge location -location {150.0 1623.125} -width 0.1
set_pin_physical_constraints -pin_name BSEL_o[5] -layers M3 -off_edge location -location {150.0 1447.445} -width 0.1
set_pin_physical_constraints -pin_name BSEL_o[6] -layers M3 -off_edge location -location {150.0 1271.765} -width 0.1
set_pin_physical_constraints -pin_name BSEL_o[7] -layers M3 -off_edge location -location {150.0 1096.085} -width 0.1
